repositoryUrl: https://github.com/Dynamsoft/camera-enhancer-docs/blob/master
repository: Dynamsoft/camera-enhancer-docs
docFullPath: https://www.dynamsoft.com
firstLevelUrl: 
docHomePage: /introduction/

productUrl: https://www.dynamsoft.com/camera-enhancer/overview/
productName: Dynamsoft Camera Enhancer

introduction: /introduction/
programming: /programming/
parameters: /parameters/
trouble-shooting: /trouble-shooting/

ios: /programming/ios/
ios-guide: /programming/ios/guide/
ios-api: /programming/ios/primary-api/
ios-api-auxiliary: /programming/ios/auxiliary-api/
ios-release-note: /programming/ios/release-note/
ios-cameraenhancer: /programming/ios/api/cameraenhancer/

introduction-license: /introduction/license/

android: /programming/android/
android-guide: /programming/android/guide/
android-api: /programming/android/primary-api/
android-api-auxiliary: /programming/android/auxiliary-api/
android-release-note: /programming/android/release-note/
android-cameraenhancer: /programming/android/primary-api/cameraenhancer/

reference: /parameters/reference/
enumerations: /parameters/enumerations/

trouble-shooting: /trouble-shooting/
license-error: /trouble-shooting/license-error/
contact-us: /trouble-shooting/contact-us/
gallery: /resources/code-gallery/
all-release-note: /resources/release-notes/
resource: /resources/

barcode-deploy-ios: /barcode-reader/programming/ios/api-reference/camera-enhancer/
barcode-deploy-android: /barcode-reader/programming/android/api-reference/camera-enhancer/

assets: /assets/
edit_icon: /assets/img-icon/edit-icon.png
smile_icon: /assets/img-icon/icon-smile.png
sad_icon: /assets/img-icon/icon-sad.png
dbr_icon: /assets/img-icon/icon-dbr.svg
dwt_icon: /assets/img-icon/icon-dwt.svg
dnt_icon: /assets/img-icon/icon-dnt.svg

overview: /camera-enhancer/overview/
download: /camera-enhancer/downloads/1000021-confirmation/

useVersionTree: true

baseurl: "/"
plugins:
  - jemoji


defaults:
  - scope:
      path: "programming/android/auxiliary-api"
    values:
      oriPath: programming/android/auxiliary-api
      additionalSearchPath:
        - programming/android/auxiliary-api-backup
        - programming/android/auxiliary-api-backup-test


defaults:
  - scope:
      path: "programming/android/auxiliary-api-backup"
    values:
      oriPath: programming/android/auxiliary-api-backup
      additionalSearchPath:
        - programming/android/auxiliary-api

defaults:
  - scope:
      path: "programming/android/auxiliary-api-backup-test"
    values:
      oriPath: programming/android/auxiliary-api-backup-test
      additionalSearchPath:
        - programming/android/auxiliary-api